CREATE TABLE [dbo].[OLE DB Destination] (
    [Business Unit]                       VARCHAR (50) NULL,
    [Cost Center Code]                    VARCHAR (50) NULL,
    [Cost Center Name]                    VARCHAR (50) NULL,
    [Location]                            VARCHAR (50) NULL,
    [Employee Number]                     VARCHAR (50) NULL,
    [Employee Last Name]                  VARCHAR (50) NULL,
    [Employee first name]                 VARCHAR (50) NULL,
    [Employee middle name initial]        VARCHAR (50) NULL,
    [Employee suffix]                     VARCHAR (50) NULL,
    [Employee nickname]                   VARCHAR (50) NULL,
    [Assignment Number]                   VARCHAR (50) NULL,
    [Employee SSN government ID]          VARCHAR (50) NULL,
    [Employee DOB]                        VARCHAR (50) NULL,
    [Employee street address 1]           VARCHAR (50) NULL,
    [Employee street address 2]           VARCHAR (50) NULL,
    [Employee street address 3]           VARCHAR (50) NULL,
    [Employee street address 4]           VARCHAR (50) NULL,
    [Employee city]                       VARCHAR (50) NULL,
    [Employee state]                      VARCHAR (50) NULL,
    [Employee postal code]                VARCHAR (50) NULL,
    [Employee country]                    VARCHAR (50) NULL,
    [Employee telephone number country]   VARCHAR (50) NULL,
    [Employee telephone number area code] VARCHAR (50) NULL,
    [Employee telephone number]           VARCHAR (50) NULL,
    [Employee cell phone country]         VARCHAR (50) NULL,
    [Employee cell phone area code]       VARCHAR (50) NULL,
    [Employee cell phone]                 VARCHAR (50) NULL,
    [Employee e-mail]                     VARCHAR (50) NULL,
    [Employee gender]                     VARCHAR (50) NULL,
    [Employee marital status]             VARCHAR (50) NULL,
    [Employee citizenship]                VARCHAR (50) NULL,
    [Employee activity code]              VARCHAR (50) NULL,
    [Person type]                         VARCHAR (50) NULL,
    [Employee type]                       VARCHAR (50) NULL,
    [Employment type]                     VARCHAR (50) NULL,
    [Supervisor]                          VARCHAR (50) NULL,
    [Last hire date]                      VARCHAR (50) NULL,
    [Seniority date]                      VARCHAR (50) NULL,
    [Termination date]                    VARCHAR (50) NULL,
    [Pay frequency]                       VARCHAR (50) NULL,
    [Shift]                               VARCHAR (50) NULL,
    [Job title]                           VARCHAR (50) NULL,
    [Job Code]                            VARCHAR (50) NULL,
    [Last check date]                     VARCHAR (50) NULL,
    [Salary Basis]                        VARCHAR (50) NULL,
    [Current pay rate]                    VARCHAR (50) NULL
);

